<a href="https://colab.research.google.com/github/hugoalexg/Python-for-Data-Science-and-Machine-Learning-Bootcamp/blob/main/2_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import NumPy as np

In [ ]:
import numpy as np

Create an array of 10 zeros

In [ ]:
arr = np.zeros(10)
print(arr)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create an array of 10 ones


In [ ]:
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Create an array of 10 fives

In [ ]:
arr[:] = 5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Create an array of the integers from 10 to 50

In [ ]:
print(np.arange(10,51))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


Create an array of all the even integers from 10 to 50


In [ ]:
print(np.arange(10,51,2))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
arr=np.arange(9)
arr=arr.reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Create a 3x3 identity matrix

In [ ]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Use NumPy to generate a random number between 0 and 1

In [ ]:
print(np.random.rand(1))

[0.55364378]


Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
print(np.random.randn(25))

[ 1.20524348  0.68825571  0.32819988  0.00867831  0.43862416 -1.81298188
  0.42220213  2.00037064  1.6114354  -0.23510888 -1.79316144 -0.00697318
  0.81026717  0.52521087  1.42107259  1.29251877  0.80981698 -1.05627164
 -0.60156056  1.0248097   1.09183223  1.60240662 -0.41096861 -0.36805382
  1.49498335]


Create the following matrix:


In [ ]:
arr = np.linspace(0.01,1,100)
arr=arr.reshape(10,10)
print(arr)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
arr = np.linspace(0,1,20)
print(arr)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print(mat[2:,1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
print(mat[3,4])

20


In [ ]:
print(mat[:3,1:2])

[[ 2]
 [ 7]
 [12]]


In [ ]:
print(mat[4])

[21 22 23 24 25]


In [ ]:
print(mat[3:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


Get the sum of all the values in mat

In [ ]:
var = np.sum(mat)
print(var)

325


Get the standard deviation of the values in mat

In [ ]:
var = np.std(mat)
print(var)

7.211102550927978


Get the sum of all the columns in mat


In [ ]:
sum_arr = np.array([0,0,0,0,0])
arr_length = sum_arr.shape[0]
for i in range(arr_length):
    sum_arr[i] = np.sum(mat[0:,i])
print(sum_arr)

[55 60 65 70 75]
